version: "3.9"

services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset_app
    ports:
      - "8088:8088"
    env_file:
      - .env
    volumes:
      - superset_home:/app/superset_home
    entrypoint: ["/app/entrypoint.sh","app"]
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: superset_db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data   # <-- bind mount (your original)

  nginx:
    env_file:
      - .env
    image: nginx:latest
    container_name: superset_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates:ro

  redis:
    image: redis:7
    container_name: superset_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  superset-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset_worker
    command: ["/app/entrypoint.sh", "worker"]
    env_file:
      - .env
    environment:
      CELERYD_CONCURRENCY: 2
    restart: unless-stopped
    depends_on:
      - superset
    volumes:
      - superset_home:/app/superset_home
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME"]

  superset-worker-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superset_worker_beat
    command: ["/app/entrypoint.sh", "beat"]
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - superset-worker
    volumes:
      - superset_home:/app/superset_home
    healthcheck:
      disable: true

volumes:
  superset_home:
  redis_data:
